### ISSUE TITLE
css cursor style

### ISSUE THREAD

**Issue by BestBugMaker** [richardtallent/vue-simple-calendar#148]
I think it will be much better if you can add **cursor: pointer** to all the events and buttons inside the calendar since I cannot add style to cv-event by myself

**Comment by richardtallent** [comment]
Here's a good explanation of why the **default** style does not use a pointer cursor for the events and buttons:

https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b#.b33l7fivt

However, you can override this behavior in your own CSS if you wish:

```CSS
.cv-header-nav button:hover,
.cv-event:hover { cursor: pointer; }
```
