### ISSUE TITLE
Cannot change font color for startTime/endTime

### ISSUE THREAD

**Issue by SincerelyUnique** [richardtallent/vue-simple-calendar#208]
Good afternoon, can you help me check why I can't change the font color?

```css
<style lang="scss" scoped>
.div{
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    color: #2c3e50;
    height: 360vh;
    width: 100%;
    margin-left: auto;
    margin-right: auto;

    .theme-default .cv-item .startTime,
    .theme-default .cv-item .endTime {
        font-weight: bold;
        color: white;    // I want to change the color to white, but not works
    }
}
```

Thank you in advance!!
